<?xml version="1.0"?>
<robot name="line_follower" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="wheel" params="prefix xyz rpy">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="${xyz}" rpy="${rpy}" />
                <material name="black" />
            </visual>
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}"
                h="${wheel_length}" xyz="${xyz}" rpy="${rpy}" />
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="${xyz}" rpy="${rpy}" />
                <material name="black" />
            </collision>
        </link>
    </xacro:macro>

    <link name="base_footprint">
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <xacro:cuboid_inertia m="10.0" l="${base_length}"
            w="${base_width}" h="${base_height}"
            xyz="0 0 ${base_height / 2}" rpy="0 0 0" />
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0" />
        </collision>
    </link>

    <xacro:wheel prefix="front_left" xyz="0 ${wheel_length / 2} 0" rpy="${pi / 2.0} 0 0" />
    <xacro:wheel prefix="front_right" xyz="0 ${-wheel_length / 2} 0" rpy="${pi / 2.0} 0 0" />
    <xacro:wheel prefix="rear_left" xyz="0 ${wheel_length / 2} 0" rpy="${pi / 2.0} 0 0" />
    <xacro:wheel prefix="rear_right" xyz="0 ${-wheel_length / 2} 0" rpy="${pi / 2.0} 0 0" />

    <joint name="base_footprint_to_base_link" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0.2" rpy="0 0 0" />
    </joint>

    <joint name="base_link_to_front_left_wheel" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel" />
        <origin xyz="${xyz_base_link_to_front_left_wheel}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_link_to_front_right_wheel" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel" />
        <origin xyz="${xyz_base_link_to_front_right_wheel}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_link_to_rear_left_wheel" type="continuous">
        <parent link="base_link" />
        <child link="rear_left_wheel" />
        <origin xyz="${xyz_base_link_to_rear_left_wheel}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_link_to_rear_right_wheel" type="continuous">
        <parent link="base_link" />
        <child link="rear_right_wheel" />
        <origin xyz="${xyz_base_link_to_rear_right_wheel}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>
</robot>